# -*- coding: utf-8 -*-
"""kmeans_clustering_sen_tran.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Doi-T6XEe-YiUK6bXK3QJ1E62NWT-5fO
"""

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer
from sklearn.cluster import KMeans

embedder = SentenceTransformer("all-MiniLM-L6-v2")

# Corpus with example sentences
corpus = ['A man is eating food.',
          'A man is eating a piece of bread.',
          'A man is eating pasta.',
          'The girl is carrying a baby.',
          'The baby is carried by the woman',
          'A man is riding a horse.',
          'A man is riding a white horse on an enclosed ground.',
          'A monkey is playing drums.',
          'Someone in a gorilla costume is playing a set of drums.',
          'A cheetah is running behind its prey.',
          'A cheetah chases prey on across a field.'
          ]
corpus_embeddings = embedder.encode(corpus)

# Perform KMeans clustering

n_clusters = 5
cluster_model = KMeans(n_clusters=n_clusters,n_init='auto')
cluster_model.fit(corpus_embeddings)
cluster_assignment = cluster_model.labels_

cluster_assignment

clustered_sentences = [[] for i in range(n_clusters)]
for sentence_id, cluster_id in enumerate(cluster_assignment):
  clustered_sentences[cluster_id].append(corpus[sentence_id])

for i,cluster in enumerate(clustered_sentences):
  print("Cluster",i+1)
  print(cluster)
  print("")

