# -*- coding: utf-8 -*-
"""paraphrase_mining.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xKlTRyy89MUPm4SK0b6SvPy7fXoWiVU_
"""

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer('all-MiniLM-L6-v2')
# Single list of sentences - Possible tens of thousands of sentences
sentences = ['The cat sits outside',
             'A man is playing guitar',
             'I love pasta',
             'The new movie is awesome',
             'The cat plays in the garden',
             'A woman watches TV',
             'The new movie is so great',
             'Do you like pizza?']

paraphrases = util.paraphrase_mining(model,sentences,show_progress_bar=True)

for paraphrase in paraphrases[0:10]:
  score,i,j  = paraphrase
  print(f"{sentences[i]:{30}} {sentences[j]:{35}} {'Score:':{5}} {score}")

